### ISSUE TITLE
Move this into the Mozilla

### ISSUE THREAD

**Issue by kdavis-mozilla** [andrenatal/git-auto-updater#1]
We should move this into Mozilla and make sure Chris and everyone else use the same repo

**Comment by andrenatal** [comment]
@kdavis-mozilla: @tilmankamp pushed some PR's here. Could you move those as well?

[This one](https://github.com/andrenatal/git-auto-updater/commit/deb61d336c5d2e45b97dc1bc3f256cd4aae54d31)

**Comment by andrenatal** [comment]
I see is there
