### ISSUE TITLE
Consider adding some slight randomness to the git-auto-updater check times

### ISSUE THREAD

**Issue by floatingatoll** [andrenatal/git-auto-updater#3]
Hi, from an operational perspective, the number of servers required to handle 100,000 requests coming in at 02:00:00 (2am) for updates all at once is very high. An error/timeout algorithm that uses a fixed timeout of, for example, 60 seconds would also suffer this same problem, and can cause a "ringing" effect where load spikes at 02:01:00, 02:02:00, 02:03:00 for a long period of time until all clients have managed to get through.

The load is significantly lower if the update time (2am) and error retry interval (60s) are varied slightly at random each time a timer is set. Sleeping 0-30 random seconds when beginning a 2am check, and setting an error retry timer of 60-75s rather than 60s, would be enough to keep clients up to date within the desired windows without causing synchronization issues.

**Comment by andrenatal** [comment]
Agreed.

**Comment by kdavis-mozilla** [comment]
We have 15 devices, this is not a problem.

**Comment by kdavis-mozilla** [comment]
@andrenatal can you close this.
